version: '3'

services:
  api:
    container_name: api
    build: '.'
    # env_file:
      # - '.env'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
      - '/app/client/'
    networks:
      - front-tier
      - back-tier
    command: "npm run local"
    # depends_on:
      # - redis
      # - db
  client:
    container_name: client
    build: '.'
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - './client:/app/client'
    links:
      - api
    depends_on:
      - api
    networks:
      - front-tier
      - back-tier
    command: "npm run client"

networks:
  front-tier:
  back-tier: